apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 3000  # Port exposed by the Service
    targetPort: 3000  # Update to reflect your application's port
